= dotfiles

📝 Some common configs that I personally use.

== Global config

The `.gitconfig` file is intended to be (at least part of) a user's
 global `~/.gitconfig`.
 
== Installation

The global Git config file is stored in the user’s home directory. Depending on yor OS:

C:\Users\<username> on Windows
~home/<username> on Linux
~root/ for sudo operations

Open git config file: git config --global --edit

== Enable VS Code command: 

For mac:
1. Launch VS Code.
2. Open the Command Palette (⇧⌘P) and type 'shell command' to find the Shell Command: Install 'code' command in PATH command.
3. Set core editor with this command: git config --global core.editor "code --wait"

== Contributing

You want to make this even more awesome? That's great! You can open a
 PR on Github (or any other repo hosting site that you may find this
 hosted)

If you fork and make your own custom changes, don't bother yourself
 proposing those changes back to the original repo. Consider
 sending me a link anyway so that I can see what cool things you're
 doing. 😉
