= dotfiles

📝 Some common configs that I personally use.

== Global config

The `.gitconfig` file is intended to be (at least part of) a user's
 global `~/.gitconfig`.
 
== Installation

Note:
I like to set VS Code as editor first to make things easier.
Set core editor with this command: git config --global core.editor "code --wait"
If this doesn't work, you'll probably need to enable vscode command first (see mac docs: https://code.visualstudio.com/docs/setup/mac#:~:text=Launch%20VS%20Code.,code'%20command%20in%20PATH%20command.).

1. Open git config file: git config --global --edit

2. Copy and paste the contents of .gitconfig

The global Git config file is stored in the user’s home directory. Depending on yor OS:

- C:\Users\<username> on Windows
- ~home/<username> on Linux
- ~root/ for sudo operations

== How to Install in Windows using script.bat

The script does the work for you! It automatically updates and copies configuration files, making sure your you're rocking the latest version always.
Only tested on Windows 11.

1. Clone or download the .zip of the main branch in this repository
2. Run the `script.bat` file by clicking on it.
   The script will perform the following steps:
   - Check if Git is installed and accessible.
   - Run 'git pull' to ensure the latest version.
   - Copy the global config files to the home directory
Once the script has finished executing, the application should be installed and configured.

== Enable VS Code command: 

For mac:
1. Launch VS Code.
2. Open the Command Palette (⇧⌘P) and type 'shell command' to find the Shell Command: Install 'code' command in PATH command.

== Contributing

You want to make this even more awesome? That's great! You can open a
 PR on Github (or any other repo hosting site that you may find this
 hosted)

If you fork and make your own custom changes, don't bother yourself
 proposing those changes back to the original repo. Consider
 sending me a link anyway so that I can see what cool things you're
 doing. 😉
